version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    labels:
      - packaging
      - docker
      - dependencies
    commit-message:
      prefix: packaging
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - ci
      - github_actions
      - dependencies
    commit-message:
      prefix: ci
      include: scope
