on:
  pull_request:
    types:
      - edited

jobs:
  detect:
    if: github.head_ref == 'release/next'
    runs-on: ubuntu-latest
    outputs:
      checked: ${{ steps.detect.outputs.checked }}
      unchecked: ${{ steps.detect.outputs.unchecked }}
      dotenv: ${{ steps.dotenv.outputs }}
    steps:
      - name: Checkbox Trigger
        id: detect
        uses: karlderkaefer/github-action-checkbox-trigger@v1.1.4
        with:
          github-token: ${{ github.token }}
          action: detect

      - name: list changes
        run: |
          echo "checked=${{ steps.detect.outputs.checked }}"
          echo "unchecked=${{ steps.detect.outputs.unchecked }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dotenv Action
        id: dotenv
        uses: falti/dotenv-action@v1.0.4
        with:
          path: ./.github/release-next.env

  update:
    runs-on: ubuntu-latest
    needs: detect
    if: ${{ contains(needs.detect.outputs.checked, needs.detect.outputs.dotenv.refresh_checkbox) }}
    steps:
      - uses: ./.github/workflows/release-next-create-pr.yaml
