name: Publish release now
on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'

jobs:
  if_merged:
    if: github.head_ref == 'release/next' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.draft.outputs.upload_url }}
    steps:
      - name: Publish release
        uses: release-drafter/release-drafter@v6.0.0
        id: draft
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          config-name: release-drafter.yaml
          publish: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete branch
        continue-on-error: true
        run: git push origin --delete 'release/next'

  do_publish:
    name: Call release workflow
    needs: if_merged
    uses: ./.github/workflows/publish.yaml
    with:
      upload_url: ${{ needs.if_merged.outputs.upload_url }}
